- hosts: "*"
  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: yes
      stat:
        path: /var/run/reboot-required
      register: reboot_required
